DROP TABLE IF EXISTS SALES_SOURCE_DATA;
CREATE TABLE SALES_SOURCE_DATA
(employee_id 	INTEGER,
WEEK_ID	INTEGER,
SALES_MON	NUMERIC(8,2),
SALES_TUE	NUMERIC(8,2),
SALES_WED	NUMERIC(8,2),
SALES_THUR	NUMERIC(8,2),
SALES_FRI	NUMERIC(8,2));